#!/usr/bin/env python3
"""
WP1a harness generator  --  MATIEC-C + CBMC as an independent second verifier.

Reads a benchmark's variable-classification sidecar (<prog>.json, the same
in/out/local map K-ESBMC's front-end emits) and its property file (props.yaml),
and emits a *tool-agnostic* C harness that:

  * declares one bounded scan loop of N cycles,
  * drives every `input` variable non-deterministically each scan
    (nondet_bool under CBMC; enumerated/random under a native smoke build),
  * calls model_scan() -- the one-scan entry point supplied by the model, and
  * after every scan checks each safety property.

The harness never touches MATIEC symbols directly.  It reaches program
variables only through the macros IN()/OUT()/VAR() defined in `bindings.h`.
That file is the *one* per-benchmark integration artifact:
  - for the real WP1a run it maps VAR(x) onto the MATIEC-generated located
    variable for x (see run_wp1a.sh), and model_scan() -> config_run__();
  - for the Docker-free smoke test it maps onto a hand-written scan function.

This separation is deliberate: the harness + property compilation below is the
reusable, verifier-independent core, and it is what this file lets you test
without Docker or CBMC.

Usage:
  gen_cbmc_harness.py <prog>.json props.yaml --scans N > harness.c
"""
import argparse, json, re, sys

# --- minimal YAML reader for the tiny props schema (no PyYAML dependency) -----
def load_props(path):
    props, cur = [], None
    for raw in open(path):
        line = raw.rstrip("\n")
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("- id:"):
            cur = {"id": s.split(":", 1)[1].strip(), "variables": []}
            props.append(cur)
        elif cur is not None and s.startswith("kind:"):
            cur["kind"] = s.split(":", 1)[1].strip()
        elif cur is not None and s.startswith("expression:"):
            cur["expression"] = s.split(":", 1)[1].strip().strip('"').strip("'")
        elif cur is not None and s.startswith("- ") and "variables_open" in cur:
            cur["variables"].append(s[2:].strip().strip('"').strip("'"))
        elif cur is not None and s.startswith("variables:"):
            cur["variables_open"] = True
    for p in props:
        p.pop("variables_open", None)
    return props

# Rewrite a boolean expression's identifiers x -> VAR(x); leave C operators
# (!,&&,||,(,)) and boolean literals alone.  Property expressions in the suite
# are already C-compatible (e.g. "!Light || Btn", "!(NS_Green && EW_Green)").
_KEYWORDS = {"true", "false", "TRUE", "FALSE"}
def cexpr(expr):
    def repl(m):
        tok = m.group(0)
        return tok if tok in _KEYWORDS else f"VAR({tok})"
    return re.sub(r"[A-Za-z_][A-Za-z0-9_]*", repl, expr)

def prop_check(p):
    pid = p["id"]
    kind = p.get("kind", "invariant")
    if kind == "mutual_exclusion":
        vs = p["variables"]
        terms = " + ".join(f"(VAR({v})?1:0)" for v in vs)
        cond = f"(({terms}) <= 1)"
        desc = f"mutual_exclusion({', '.join(vs)})"
    else:
        e = cexpr(p["expression"])
        cond = e if kind == "invariant" else f"(!({e}))"  # absence: bad expr must not hold
        desc = f"{kind}: {p['expression']}"
    return pid, cond, desc

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("kinds_json")
    ap.add_argument("props_yaml")
    ap.add_argument("--scans", type=int, default=6)
    args = ap.parse_args()

    kinds = json.load(open(args.kinds_json))["kinds"]
    inputs = [v for v, k in kinds.items() if k == "input"]
    props = load_props(args.props_yaml)
    checks = [prop_check(p) for p in props]

    out = sys.stdout.write
    out("/* AUTO-GENERATED by gen_cbmc_harness.py -- WP1a MATIEC-C + CBMC harness.\n"
        "   Verifier-independent: property logic identical whatever produces model_scan(). */\n")
    out('#include "bindings.h"\n\n')
    # nondet input source. Bodyless under CBMC -> CBMC auto-havocs it (true
    # nondeterminism). Native smoke builds (-DWP1A_NATIVE) link nondet_native.c,
    # which supplies a rand() body. CBMC is the DEFAULT so verification never
    # depends on CBMC predefining a detection macro (a wrong guard silently turns
    # nondet into rand() and assertions into printf -- an unsound run).
    out("int nondet_bool(void);\n\n")
    out("#ifdef WP1A_NATIVE\n"
        "  #include <stdio.h>\n"
        "  static int __viol = 0;\n"
        "  #define __CPROVER_assume(x) do{ if(!(x)) return 0; }while(0)\n"
        "  #define __CPROVER_assert(x,msg) do{ if(!(x)){ printf(\"VIOLATED %s\\n\",(msg)); __viol=1; } }while(0)\n"
        "#endif\n\n")
    out(f"#define N_SCANS {args.scans}\n\n")
    out("int main(void){\n  model_init();\n")
    out("  for (int s = 0; s < N_SCANS; s++){\n")
    for v in inputs:
        out(f"    IN({v}) = nondet_bool();\n")
    out("    model_scan();\n")
    for pid, cond, desc in checks:
        out(f'    __CPROVER_assert({cond}, "prop {pid}  ({desc})");\n')
    out("  }\n")
    out("#ifdef WP1A_NATIVE\n  return __viol;\n#else\n  return 0;\n#endif\n}\n")

if __name__ == "__main__":
    main()
