/* AUTO-GENERATED by gen_cbmc_harness.py -- WP1a MATIEC-C + CBMC harness.
   Verifier-independent: property logic identical whatever produces model_scan(). */
#include "bindings.h"

int nondet_bool(void);

#ifdef WP1A_NATIVE
  #include <stdio.h>
  static int __viol = 0;
  #define __CPROVER_assume(x) do{ if(!(x)) return 0; }while(0)
  #define __CPROVER_assert(x,msg) do{ if(!(x)){ printf("VIOLATED %s\n",(msg)); __viol=1; } }while(0)
#endif

#define N_SCANS 6

int main(void){
  model_init();
  for (int s = 0; s < N_SCANS; s++){
    IN(Btn) = nondet_bool();
    model_scan();
    __CPROVER_assert(!VAR(Light) || VAR(Btn), "prop A  (invariant: !Light || Btn)");
    __CPROVER_assert((!(VAR(Light))), "prop B  (absence: Light)");
  }
#ifdef WP1A_NATIVE
  return __viol;
#else
  return 0;
#endif
}
